# Generated by Django 3.0.5 on 2020-10-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='disp_name',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
