# Generated by Django 3.1.2 on 2020-10-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_app', '0005_auto_20201015_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=500)),
        ),
    ]
