# Generated by Django 3.1.2 on 2020-10-15 13:17

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stack_app', '0006_auto_20201015_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=500, populate_from=('question',), unique=True, verbose_name='slug'),
        ),
    ]
