# Generated by Django 3.1.2 on 2020-10-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_app', '0008_auto_20201020_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
