# Generated by Django 3.1.2 on 2020-10-20 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stack_app', '0009_auto_20201020_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
