# Generated by Django 3.1.2 on 2020-10-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack_app', '0012_remove_profile_disp_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
