# Generated by Django 3.1.2 on 2020-10-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_app', '0013_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
